### ISSUE TITLE
Confused with hash validation

### ISSUE THREAD

**Issue by c0debreaker** [dxa4481/clientHashing#2]
Here is your code

```js
app.post('/login', function(req, res){
    var usersHash = crypto.createHash('sha256').update(req.body.hash, 'utf8').digest("hex");
    res.json({success: (hash == usersHash)})
});
```

My guess is `req.body.hash` is the hash sent by the web application. However, where is it comparing it from? Is there a database? How would `crypto.createHash` create a `usersHash` that is the same as `req.body.hash`?

**Comment by dxa4481** [comment]
Hi @c0debreaker 
This is example server code, that contains a user's hash that would normally be stored in a database. For the sake of the example, instead of the hash being stored in a database, it's just hard coded at the top, which is what the user request is checked against.
